### PR TITLE
Automated workflow

### PR DESCRIPTION
**Pull request by noamross**
Follow up to #60

### CODE REVIEW

**Comment by noamross** [comment]
@scolombe @thibautjombart This is merged, as that was the only way to test the full work flow.  Please look at the Join and People pages to check that everything looks good to you. I note that I cleaned up a few site/twitter/github links in the AirTable.

The site build is scheduled to run every night at midnight GMT time, to reflect changes in the AirTable.  You can also manually trigger a build at https://github.com/reconhub/reconhub.github.io/actions/workflows/build-site.yaml, by hitting the "Run Workflow" button. (Note the workflow can be run on any branch to test, but only changes to the master branch will deploy, by being pushed to the `gh-pages` branch.)

**Comment by thibautjombart** [comment]
Awesome! It looks all fine to me except for Cici Bauer, who appears twice on the website with slightly different descriptions - I am guessing two separate entries in AirTable? Otherwise, the improvements you have made are amazing. :)

**Comment by scolombe** [comment]
Fantastic, thank you! I doubled check for Cici, and that was an error on the Google spreadsheet. It is fixed now on google spreadsheet, I kept the most up-to-date information.

**Comment by scolombe** [comment]
And fixed on the Airtable too now - I  guess we can archive the google spreadsheet.

**Pull request merged**
