### PR TITLE
Updated photo

### PR DESCRIPTION
**Pull request by hannahbrindle**

### CODE REVIEW

**Review by thibautjombart — CHANGES_REQUESTED** [review]
Thanks for this. There are 3 junk files (the `DS_Store`) in the PR. Could you remove them and push?

**Comment by hannahbrindle** [comment]
Ok I reverted the push to the .DS_Store in my fork but I can't seem to create a new pull request?

Hannah
________________________________

**Comment by thibautjombart** [comment]
You only need to push to the same branch you made the PR from. Thanks, it seems like only one of the 3 junk file was removed. If you can remove the other 2 that'd be brilliant, then I'll merge the PR

**Comment by hannahbrindle** [comment]
Ok, I've added a .gitignore and pushed now so hopefully removed?
________________________________

**Comment by thibautjombart** [comment]
I am afraid adding the .gitignore does not remove previously committed files. Can you use the same approach on the remaining files as you did for the one you successfully removed?

**Comment by thibautjombart** [comment]
I have taken the photo from your PR and manually added it to master so this PR can be closed. Thanks for the new pic!

**Pull request closed without merging**
